# Generated by Django 6.0.6 on 2026-06-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер квартиры')),
                ('area', models.FloatField(verbose_name='Площадь')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('rooms_count', models.IntegerField(verbose_name='Количество комнат')),
                ('deadline', models.DateField(verbose_name='Срок сдачи')),
                ('type', models.CharField(choices=[('commercial', 'Коммерческий'), ('residential', 'Жилой'), ('penthouse', 'Пентхаус')], max_length=20, verbose_name='Тип квартиры')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
    ]
