# Generated by Django 6.0.6 on 2026-06-25 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер блока')),
                ('floors_count', models.PositiveIntegerField(verbose_name='Количество этажей')),
                ('entrance_count', models.PositiveIntegerField(verbose_name='Количество подъездов')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение блока')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название объекта')),
                ('description', models.TextField(verbose_name='Описание объекта')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение объекта')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес объекта')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apartments', to='estate.block', verbose_name='Блок'),
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('block', 'number')},
        ),
        migrations.AddField(
            model_name='block',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='estate.object', verbose_name='Объект'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('object', 'number')},
        ),
    ]
